version: '3.4'
services:
  linter:
    build:
      context: .
      target: dev
    volumes:
      # Mount these in so we pick up edits in dev, without having to re-build
      - "./bin:/src/bin"
      - "./lib:/src/lib"
      - "./test:/src/test"
    command: npm test