version: '3.2'
services:
  linter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount these in so we pick up edits in dev, without having to re-build
      - "./bin:/src/bin"
      - "./lib:/src/lib"
      - "./test:/src/test"
    command: npm test