steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v5.4.1:
        run: linter

  - wait

  - label: ":docker: :rocket: Latest"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-plugin-linter-deploy
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_PLUGIN_DOCKER_LOGIN_USERNAME: /pipelines/buildkite/plugin-linter-deploy/docker-login-username
            DOCKER_LOGIN_PASSWORD: /pipelines/buildkite/plugin-linter-deploy/docker-login-password
      - docker-login#v3.0.0: ~
      - docker-compose#v5.4.1:
          config: docker-compose.prod.yml
          build: linter
          push:
            - linter:buildkite/plugin-linter
    if: |
      build.branch == 'master'
  - label: ":docker: :rocket: Tag"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-plugin-linter-deploy
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_PLUGIN_DOCKER_LOGIN_USERNAME: /pipelines/buildkite/plugin-linter-deploy/docker-login-username
            DOCKER_LOGIN_PASSWORD: /pipelines/buildkite/plugin-linter-deploy/docker-login-password
      - docker-login#v3.0.0: ~
      - docker-compose#v5.4.1:
          config: docker-compose.prod.yml
          build: linter
          push:
            - linter:buildkite/plugin-linter:${BUILDKITE_TAG}
    if: |
      build.tag != null
