steps:
  - label: ":mocha:"
    command: "npm run test"
    plugins:
      - docker-compose#v4.9.0:
          run: linter

  - label: ":eslint:"
    command: "npm run lint"
    plugins:
      - docker-compose#v4.9.0:
          run: linter
