steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v4.13.0:
        run: linter

  - wait

  - label: ":docker: :rocket: Latest"
    plugins:
      docker-login#v2.1.0: ~
      docker-compose#v4.13.0:
        config: docker-compose.prod.yml
        push:
          - linter:buildkite/plugin-linter
    if: |
      build.branch == 'master'
  - label: ":docker: :rocket: Tag"
    plugins:
      docker-login#v2.1.0: ~
      docker-compose#v4.13.0:
        config: docker-compose.prod.yml
        push:
          - linter:buildkite/plugin-linter:${BUILDKITE_TAG}
    if: |
      build.tag != null
