steps:
  - label: ":mocha:"
    command: "npm run test"
    plugins:
      docker-compose#v2.0.0:
        run: linter

  - label: ":eslint:"
    command: "npm run lint"
    plugins:
      docker-compose#v2.0.0:
        run: linter

  - wait

  - label: ":docker:"
    branches: master
    plugins:
      docker-login#v1.0.0: ~
      docker-compose#v2.0.0:
        config: docker-compose.prod.yml
        push:
          - linter:buildkite/plugin-linter