steps:
  - label: ":mocha:"
    plugins:
      docker-compose#v2.0.0:
        run: linter
  - wait
  - label: ":docker:"
    branches: master fix-tests
    plugins:
      docker-compose#v2.0.0:
        config: docker-compose.prod.yml
        push:
          - linter:buildkite/plugin-linter